<?php

namespace Container2TT5S6B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWeatherLocationCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\WeatherLocationCommand' shared autowired service.
     *
     * @return \App\Command\WeatherLocationCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/WeatherLocationCommand.php';

        $container->privates['App\\Command\\WeatherLocationCommand'] = $instance = new \App\Command\WeatherLocationCommand(($container->privates['App\\Service\\WeatherUtil'] ?? $container->load('getWeatherUtilService')), ($container->privates['App\\Service\\LocationUtil'] ?? $container->load('getLocationUtilService')));

        $instance->setName('weather:location');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
