<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTbi6gPj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTbi6gPj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTbi6gPj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTbi6gPj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTbi6gPj\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tbi6gPj',
    'container.build_id' => 'a0e11e88',
    'container.build_time' => 1706525872,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTbi6gPj');
