<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9hcwyxP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9hcwyxP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9hcwyxP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9hcwyxP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9hcwyxP\App_KernelDevDebugContainer([
    'container.build_hash' => '9hcwyxP',
    'container.build_id' => '9dec1327',
    'container.build_time' => 1698418995,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9hcwyxP');
