<?php

namespace ContainerRAXPkqM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocationUtilService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\LocationUtil' shared autowired service.
     *
     * @return \App\Service\LocationUtil
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/LocationUtil.php';

        return $container->privates['App\\Service\\LocationUtil'] = new \App\Service\LocationUtil(($container->privates['App\\Repository\\LocationRepository'] ?? $container->load('getLocationRepositoryService')));
    }
}
